apiVersion: v1
kind: Pod
metadata:
  name: initcontainer
spec:
  initContainers:
  - name: my-init
    image: busybox
    command: ["/bin/bash","-c","sleep 70"]
  containers: 
  - name: my-nginx
    image: nginx
    
