apiVersion: v1
kind: Pod
metadata:
  name: multi-containers
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
  - name: alpine
    image: alpine
    command: ["watch", "wget", "--server-response", "http://localhost"]
