apiVersion: v1
kind: Pod
metadata:
  name: test-job
spec:
  containers:
  - name: test
    image: python:3-alpine
    command: ["python"]
    args: ["-c","import time; print('Starting'); time.sleep(30); print('Done')"]
    #restartPolicy: Never
