apiVersion: apps/v1
kind: Deployment
metadata:
  name: californiaapp
spec:
  replicas: 10
  selector:
    matchLabels:
      app: californiaapp
  template:
    metadata:
      name: californiaapp
      labels:
        app: californiaapp
    spec:
      containers:
      - name: californiaapp
        image: subaniprasad/californiaapp:1

---
apiVersion: v1
kind: Service
metadata:
  name: californiaapp

spec:
  selector:
    app: californiaapp
  ports:
  - name: http 
    port: 80
    nodePort: 32222

  type: NodePort
