apiVersion: v1
kind: Secret
metadata:
  name:  mysql-secrets
data:
   mysql_user:  cHJhc2Fk
   mysql_user_password: cHJhc2Fk
   mysql_root_password: cGFzc3dvcmQ=
type: Opaque
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-configmap
data:
  .my.cnf: |
    [mysql]
    user=$MYSQL_USERNAME
    password=$MYSQL_PASSWORD
    [mysqld]
    pid-file        = /var/run/mysqld/mysqld.pid
    socket          = /var/run/mysqld/mysqld.sock
    default_authentication_plugin= mysql_native_password
    port            = 3306
    datadir         = /var/lib/mysql
    default-storage-engine = InnoDB
    character-set-server = utf8
    general_log_file        = /var/log/mysql/mysql.log
    log_error = /var/log/mysql/error.log

---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql-database
spec:
  volumes:
  - name: mysql-config-volume
    configMap:
      name: mysql-configmap
      items:
        - key: .my.cnf
          path: .my.cnf

  containers:
  - name: mysql
    image: mysql:5.7
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: mysql_root_password
      - name: MYSQL_USER
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: mysql_user
      - name: MYSQL_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-secrets
            key: mysql_user_password
      - name: MYSQL_DATABASE
        value: prasad
    volumeMounts:
    - name: mysql-config-volume
      mountPath: /root/      
