apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prasad
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods","services"]
    verbs: ["get","list","watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-role
  namespace: default
subjects: 
- kind: User
  name: prasad
roleRef:
  kind: Role
  name: prasad
  apiGroup: rbac.authorization.k8s.io