apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: myadmin
  name: myadmin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: myadmin
    spec:
      containers:
      - image: phpmyadmin/phpmyadmin
        imagePullPolicy: Always
        name: phpmyadmin
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        env:
          - name: PMA_ARBITRARY
            value: '1'

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myadmin
  name: myadmin
spec:
  ports:
  - name: http
    port: 80
    nodePort: 0
  selector:
    app: myadmin
  type: NodePort