apiVersion: kubedb.com/v1alpha1
kind: MySQL
metadata:
  name: mysql-quickstart
spec:
  version: "8.0-v2"
  #replicas: 3
  storageType: Durable
  storage:
    storageClassName: "managed-nfs-storage"
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  terminationPolicy: DoNotTerminate