apiVersion: v1
kind: Pod
metadata:
  name: californiaapp
  labels:
    app: californiaapp
spec:
  volumes:
  - name: pv-dynamic
    persistentVolumeClaim:
      claimName: californiaapp-data
  containers:
  - name: californiaapp
    image: subaniprasad/californiaapp:1
    volumeMounts:
    - name: pv-dynamic
      mountPath: /usr/local/apache2/htdocs/


---
apiVersion: v1
kind: Service
metadata:
  name: californiaapp

spec:
  selector:
    app: californiaapp
  ports:
  - name: http
    port: 80
    nodePort: 0

  type: NodePort
